### ISSUE TITLE
Not an issue: how to read more data

### ISSUE THREAD

**Issue by cmarsocci** [tanersahincom/NFCAndroidExample#2]
Hi there,
That's not an issue but a question
I'm trying to read more data with the Card Id in the nfc read mode, I can't find the right methods to do it.

How can I read the manufacturer Id for example? I'm pretty sure this value it's in the first memory sector of the card, near to the Id which the app already reads, how can I "extend" the funcionalitiy?

Thanks

**Comment by tanersahindotnet** [comment]
There is a UID for that. However, do not go building an application which depends on this. There is a lot of duplications in the world due to fakes. Also the manufacturers sometimes use the same IDs till they know that they are going to different usage streams.  The UID is barely used for identifying the source of the card.

**Comment by carminemars** [comment]
Hi Taner, thanks for answering me.
Ok got it for the UID I'll try.
About the duplication, I thought the manufacturer ID was unique a least between official manufacturer, anyways, I understand it's not the best method to authenticate someone or something. 

In your opinion for a clocking app could be enough secure?  Assigning one ID per person

Thanks a lot!

**Comment by cmarsocci** [comment]
Hi Taner, thanks for answering me.
Ok got it for the UID I'll try.
About the duplication, I thought the manufacturer ID was unique a least between official manufacturer, anyways, I understand it's not the best method to authenticate someone or something.

In your opinion for a clocking app could be enough secure? Assigning one ID per person

Thanks a lot!

**Comment by tanersahindotnet** [comment]
Yes i think that it will be enough secure for a clocking app
